config/routes.rb
  Rails.application.routes.draw do
    get 'books/new'
    root to:'homes#top'
    post'books' => 'books#create'
    get 'books' => 'books#index', as: 'index_book'
    get 'books/:id' => 'books#show', as: 'book'
    get 'books/:id/edit' => 'books#edit', as: 'edit_book'
    patch 'books/:id' => 'books#update', as: 'update_book'
    delete 'books/:id' => 'books#destroy', as: 'destroy_book'
  
  
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
  class BooksController < ApplicationController
    def new
      @book = Book.new
    end
  
    def create
      @book = Book.new(book_params)
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        render :index
      end
    end
  
    def index
     @books = Book.all.order(id: "ASC")
     @book = Book.new
    end
  
    def show
      @book = Book.find(params[:id])
    end
  
    def edit
      @book = Book.find(params[:id])
    end
  
    def update
        @book = Book.find(params[:id])
        @book.update(book_params)
      if @book.save
        flash[:notice] = "Book was successfully destroyed."
        redirect_to book_path(@book.id)
      else
        render :edit
      end
    end
  
    def destroy
      flash[:notice] = "Book was successfully destroyed."
      book = Book.find(params[:id])
      book.destroy
      redirect_to '/books'
    end
  
    private
    def book_params
      params.require(:book).permit(:title, :body)
    end
  end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
<%= @book.errors.count %>errors prohibited this book from being saved:
<ul>
    <% @book.errors.full_messages.each do |message| %>
    <li>
       <%= message %>
    </li>
    <% end %>
</ul>
<% end %>

<%= form_with model: @book, url: update_book_path(@book.id), method: :patch, local:true do |f|%>

<labl>Title</labl>
<div class="text">
<%= f.text_field :title %>
</div>

<labl>Body</labl>
<div class="text">
<%= f.text_area :body %>
</div>

<div class="submit">
<%= f.submit 'Update Book' %>
</div>

<% end %>

<span><%= link_to 'Show', book_path(@book.id) %></span>
|
<span><%= link_to 'Back', index_book_path(@books) %></span>

app/views/books/index.html.erb
    <%if flash[:notice] %>
     <p id="notice">
         <%= flash[:notice] %>
     </p>
     <% end %>
    
    <h1>Books</h1>
        <table>
            <thead>
            <tr>
               <th class="title">Title</th>
               <th class="body">Body</th>
               <th></th>
            </tr>
            </thead>
            <tbody>
            <% @books.each do |book| %>
            <tr>
               <td class="title"><%= book.title %></td>
                <td class="body"> <%= book.body %></td>
                <td><%= link_to 'Show', book_path(book) %></td>
                <td><%= link_to 'Edit', edit_book_path(book) %></td>
                <td><%= link_to 'Destroy', destroy_book_path(book), method: :delete,"data-confirm" => "Are you sure？" %></td>
            </tr>
            <% end %>
            </tbody>
        </table>
    
    
    <h1>New Book</h1>
    <% if @book.errors.any? %>
    <%= @book.errors.count %>errors prohibited this book from being saved:
    <ul>
        <% @book.errors.full_messages.each do |message| %>
        <li>
           <%= message %>
        </li>
        <% end %>
    </ul>
    <% end %>
    
    <%= form_with model: @book, url: '/books', method: :post, local:true do |f| %>
    
    <labl>Title</labl>
    <div class="text">
    <%= f.text_field :title %>
    </div>
    
    <labl>Body</labl>
    <div class="text">
    <%= f.text_area :body %>
    </div>
    
    <div class="subbmit">
    <%= f.submit 'Create Book' %>
    </div>
    
    <% end %>
    
    

app/views/books/show.html.erb
  <%if flash[:notice] %>
  <p id="notice">
      <%= flash[:notice] %>
  </p>
  <% end %>
   
   <p>
   <strong>Title:</strong>
   <%= @book.title %>
   </p>
   
   
   <p>
   <strong>Body:</strong>
   <%= @book.body %>
   </p>
   
   
   <span><%= link_to 'Edit', edit_book_path(@book.id) %></span>
   |
   <span><%= link_to 'Back', index_book_path(@books) %></span>
   

app/views/homes/top.html.erb
  <h1>ようこそBookersへ！</h1>
  
  <p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
  <p>印象を共有し交換することができます</p>
  <p>
    <%= link_to 'Start', index_book_path(@books) %>
  </>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>